### ISSUE TITLE
Bypass unescaped dot inside regex validation

### ISSUE THREAD

**Issue by hansmach1ne** [PortSwigger/url-cheatsheet-data#3]
If say regex validation is used for `vulnerable.test.com`
Bypass: `vulnerableztest.com`

Instead of a dot, any character can be used, since dot matches everything. Attacker would need to buy this domain for abuse, though,

**Comment by d0ge** [comment]
Thank you very much for your contribution to the URL Validation Bypass Cheat Sheet. The unescaped dot in regex validation bypass is now included in the cheat sheet. If you'd like to test it, please enter your test domain into the allowed domain input field. The selected wordlist can be empty for this type of attack.

Cheers!
